### ISSUE TITLE
Change from today to overdue doesn't show items due today

### ISSUE THREAD

**Issue by imaginarythomas** [dwaring87/rtm-cli#4]
Latest changelog says alias for today was changed to overdue. Overdue does not list items due today and 'today' is no longer a valid command.

**Comment by dwaring87** [comment]
I've included an alias command really just to serve as an example of what they can do.  I changed the command from the `today` command to the `overdue` command since I thought it was easier to understand what the filter is doing.

The `overdue` command is supposed to show tasks that are past due (so it's purposefully not showing tasks due today).

If you want the previous `today` command you can add the following to your personal config file (`~/.rtm.json`):

```
"aliases": [
    {
      "name": "today",
      "description": "Display tasks with a priority, due or completed today, or overdue",
      "command": "lsp",
      "args": "(not priority:none and status:incomplete) or completed:today or (dueBefore:tomorrow and status:incomplete)"
    }
  ]
```
